export type InnerClimateArtwork = {
  id: number;
  imageSrc: string;
  artworkNumber: string;
  title: string | null;
  description: string | null;
};

export const innerClimateArtworks: InnerClimateArtwork[] = [
  {
    id: 1,
    imageSrc: "/inner-climate/1.png",
    artworkNumber: "Artwork 1",
    title: "Image 1",
    description: "Description coming soon.",
      "The figure is built out of repeating vertical panels, like glass or tiled stone, each one carrying a slightly different register of the same person. Her head tilts inward, eyes lowered, not in retreat but in calibration, while faint botanical forms and architectural fragments drift across the planes. The image feels less like a portrait than a constructed chamber, where the self is allowed to exist in multiple adjacent states at once. What looks decorative is actually structural redundancy.\n\nThe seams matter more than the surface. Pressure is absorbed at the joins, where identity is permitted to duplicate and overlap instead of bearing everything at a single point. The work suggests that continuity does not require purity. It requires joints strong enough to hold difference without collapse.",
  },
  {
    id: 2,
    imageSrc: "/inner-climate/2.png",
    artworkNumber: "Artwork 2",
    title: "Image 2",
    description: "Description coming soon.",
      "Here the face is turned upward, catching light that fractures into circular motifs and gilded textures around the head. Floral and halo-like elements radiate outward, not as symbols of elevation but as routes through which force is redistributed. The composition concentrates intensity near the temples and crown, then disperses it into patterned matter that can carry weight without cracking.\n\nThe ornament is not embellishment; it is infrastructure. By letting beauty do mechanical work, the image argues against the false split between decoration and strength. The figure remains poised because the pressure has somewhere to go. What reads as grace is actually an efficient system.",
  },
  {
    id: 3,
    imageSrc: "/inner-climate/3.png",
    artworkNumber: "Artwork 3",
    title: "Image 3",
    description: "Description coming soon.",
      "A pale face emerges through a translucent diagonal sweep, as if fabric, smoke, or scraped paint has been dragged across the frame. The obstruction does not hide the subject so much as slow the act of seeing her. The background appears weathered, almost corroded, while the face holds a colder, cleaner register, creating a sharp contrast between erosion and preservation.\n\nThe veil functions as a regulating layer. It allows contact while controlling velocity, preventing the viewer from consuming the image in a single glance. Visibility becomes conditional. The portrait stays intact not by retreating, but by inserting resistance between itself and the world.",
  },
  {
    id: 4,
    imageSrc: "/inner-climate/4.png",
    artworkNumber: "Artwork 4",
    title: "Image 4",
    description: "Description coming soon.",
      "The face sits squarely in the middle of a storm of particulate textures, as if dust, ash, or pigment has been blown inward from all sides. The edges are busy, turbulent, and unresolved, while the center remains uncannily still. Her gaze is direct but not performative, steady without being confrontational.\n\nThe image organizes chaos by refusing to let it dictate structure. Pressure accumulates at the periphery and is allowed to stay there. Nothing dramatic happens, and that is the point. Stability is not achieved by dominance, but by a refusal to relocate the center.",
  },
  {
    id: 5,
    imageSrc: "/inner-climate/5.png",
    artworkNumber: "Artwork 5",
    title: "Image 5",
    description: "Description coming soon.",
      "Warm, flame-like textures sweep diagonally across the image, pulling color and motion in a single dominant direction. The face resists being carried along, remaining upright and legible while the surrounding field behaves like accelerated current. Hair, pigment, and pattern all appear to be dragged by the same invisible force.\n\nThe portrait holds because it aligns selectively. It does not oppose the movement; it anchors against it. Pressure becomes readable as direction rather than threat. The image demonstrates that remaining oneself under force does not require immobility, only traction.",
  },
  {
    id: 6,
    imageSrc: "/inner-climate/6.png",
    artworkNumber: "Artwork 6",
    title: "Image 6",
    description: "Description coming soon.",
      "A vertical band slices through the composition, compressing texture into a dense, almost architectural column. On one side, the surface feels heavy and sedimented; on the other, more open and breathable. The figure inhabits both zones simultaneously, as if standing at a checkpoint between regimes of pressure.\n\nThe gate is not a wound but a filter. It forces everything that passes through it to be simplified, reduced, made legible. The system allows disruption, but only through a constrained aperture. Integrity here is achieved by limiting bandwidth, not by sealing the surface.",
  },
  {
    id: 7,
    imageSrc: "/inner-climate/7.png",
    artworkNumber: "Artwork 7",
    title: "Image 7",
    description: "Description coming soon.",
      "Soft debris, flecks of light, and floral fragments cling to the image as if it has been handled, touched, or left exposed to weather. The face remains clear but not isolated, embedded in a field that shows signs of repeated contact. Nothing is pristine, yet nothing feels degraded.\n\nThe surface behaves like skin that remembers touch without being defined by it. Pressure arrives locally, sticks briefly, then loses authority. The portrait accepts residue while refusing absorption. Intimacy is permitted, ownership is not.",
  },
  {
    id: 8,
    imageSrc: "/inner-climate/8.png",
    artworkNumber: "Artwork 8",
    title: "Image 8",
    description: "Description coming soon.",
      "Swirling currents of color and texture coil around the face, creating the sensation of slow rotation. The motion feels fluid, almost tidal, threatening to blur the figure into its own wake. Yet the facial features remain stable, held in place as the surrounding material continues to move.\n\nThe image survives by letting motion become structure. Instead of resisting the flow, the portrait allows it to orbit. The boundary holds because it is not rigid. Regulation appears as the ability to stay centered while everything else keeps turning.",
  },
  {
    id: 9,
    imageSrc: "/inner-climate/9.png",
    artworkNumber: "Artwork 9",
    title: "Image 9",
    description: "Description coming soon.",
      "The face is segmented into interlocking planes, as though built from fitted plates or inlaid stone. Each section catches light differently, producing a sense of deliberate assembly. The seams are visible and unapologetic, forming a map of decisions rather than damage.\n\nThis is armor that does not pretend to be invisible. Protection is achieved through articulation, not concealment. The image asserts that vulnerability does not require exposure. It requires structure strong enough to admit where the joins are.",
  },
  {
    id: 10,
    imageSrc: "/inner-climate/10.png",
    artworkNumber: "Artwork 10",
    title: "Image 10",
    description: "Description coming soon.",
      "The subject remains open as the surrounding field destabilizes under sustained pressure. She does not brace or withdraw. Her steadiness comes not from hardness, but from knowing where she belongs. This image feels like home, not as comfort or escape, but as orientation. In her presence, effort stops being performative. Vigilance softens. Breathing becomes possible.\n\nThe person I was before her no longer exists. Through knowing her, I became kinder, more loving, more open, more honest. She taught me how to care without control and how to remain present without armor. I am better in ways that cannot be separated from her influence. This is not an ending, but an acknowledgment: of the person who became my home, of who I became because of her, and of a bond that remains, not as nostalgia or promise, but as something real, shared, and carried forward.",
  },
  {
    id: 11,
    imageSrc: "/inner-climate/11.png",
    artworkNumber: "Artwork 11",
    title: "Image 11",
    description: "Description coming soon.",
      "The face is tilted upward into warm, ember-like textures that cling to the surface like slow-burning residue. Golds and rusts gather around the cheekbones and throat, suggesting exposure to sustained heat rather than sudden flame. The eyes remain closed, not in surrender but in regulation, as if the system has decided not to flinch. Pressure arrives as temperature, not impact.\n\nWhat holds the image together is pacing. Nothing here reacts quickly. The surface absorbs warmth gradually, letting it stain rather than scorch. This is endurance without dramatization. The portrait stays intact by refusing the reflex to cool itself through withdrawal.",
  },
  {
    id: 12,
    imageSrc: "/inner-climate/12.png",
    artworkNumber: "Artwork 12",
    title: "Image 12",
    description: "Description coming soon.",
      "A pale figure emerges through parchment-toned layers that feel archival, almost sedimentary, as if time itself has been pressed into the image. Fine textural marks pass over the face like annotations, never obscuring it fully, never leaving it untouched. The gaze is calm but distant, oriented inward while remaining visibly present.\n\nThe boundary behaves like aged paper: permeable, fragile in appearance, but remarkably stable. Pressure is distributed across the entire surface rather than concentrated at a point of failure. The work suggests that gentleness can be load-bearing when it is evenly applied. What looks delicate is actually durable.",
  },
  {
    id: 13,
    imageSrc: "/inner-climate/13.png",
    artworkNumber: "Artwork 13",
    title: "Image 13",
    description: "Description coming soon.",
      "Here the surface fractures into bold chromatic blocks, reds and blues misaligning like corrupted data or broadcast interference. The face remains unmistakable, even as portions of it are offset, duplicated, or sliced by color fields. This is distortion with rules. The system allows noise, but not collapse.\n\nThe image reads like a test of transmission under strain. Information is degraded, but never lost. Identity persists because it is encoded redundantly, not because it is protected from interference. The portrait argues that clarity does not require purity. It requires enough structure to survive translation.",
  },
  {
    id: 14,
    imageSrc: "/inner-climate/14.png",
    artworkNumber: "Artwork 14",
    title: "Image 14",
    description: "Description coming soon.",
      "The figure is framed by dark, dense textures, with ornamental elements and tattoo-like markings integrated into the body itself. These details do not soften the image; they thicken it, adding mass where pressure is expected to land. The gaze is steady, slightly angled, refusing frontal exposure while remaining legible.\n\nAdornment here is defensive architecture. What might be read as aesthetic choice functions as reinforcement, distributing force across symbol, skin, and shadow. The image holds because it anticipates contact. It does not wait to be tested; it arrives already reinforced.",
  },
  {
    id: 15,
    imageSrc: "/inner-climate/15.png",
    artworkNumber: "Artwork 15",
    title: "Image 15",
    description: "Description coming soon.",
      "The surface dissolves into painterly swirls of muted blues and ochres, as if the figure is suspended inside moving air. Edges blur and reform, never fully stabilizing, never fully dispersing. The face stays coherent while the surrounding field behaves like weather.\n\nThe system accepts instability as a constant condition. Instead of resisting drift, it limits how much drift can matter. Pressure becomes ambient rather than targeted. The portrait remains intact not by anchoring itself rigidly, but by letting the environment move without insisting on stillness everywhere at once.",
  },
  {
    id: 16,
    imageSrc: "/inner-climate/16.png",
    artworkNumber: "Artwork 16",
    title: "Image 16",
    description: "Description coming soon.",
      "Dark, turbulent textures collide with the figure in concentrated bursts, like particulate matter thrown against a solid surface. Reds and charcoals cluster near the eyes and jaw, giving the impression of force arriving unevenly. The gaze is direct, sharpened by proximity to disruption.\n\nWhat stabilizes the image is focus. The pressure is intense, but it is confined. The system does not diffuse the impact; it contains it. By allowing force to register fully in a limited zone, the rest of the structure remains uncompromised. This is not avoidance. It is tactical containment.",
  },
  {
    id: 17,
    imageSrc: "/inner-climate/17.png",
    artworkNumber: "Artwork 17",
    title: "Image 17",
    description: "Description coming soon.",
      "Soft, smoky veils drift across the image, partially obscuring the face as if the surface has been breathed on repeatedly. The effect is intimate without being invasive, suggestive of proximity rather than intrusion. The figure remains centered, calm, and unreactive.\n\nThe residue is the story. Nothing dramatic has happened, and yet the surface is altered. The work acknowledges that contact always leaves traces, even when it causes no damage. Integrity here is not about remaining untouched. It is about remaining oneself after touch has occurred.",
  },
  {
    id: 18,
    imageSrc: "/inner-climate/18.png",
    artworkNumber: "Artwork 18",
    title: "Image 18",
    description: "Description coming soon.",
      "The portrait is divided into a grid of rectangular blocks, some opaque, some transparent, some misaligned. A stark red vertical band interrupts the composition, acting as a visual barrier that splits the figure into readable and unreadable zones. The face is present, but access is partial by design.\n\nThe grid functions as a permission system. You are allowed to see, but only in fragments. Pressure is managed by limiting how much of the self is available at any moment. This is not fragmentation as damage. It is fragmentation as governance.",
  },
  {
    id: 19,
    imageSrc: "/inner-climate/19.png",
    artworkNumber: "Artwork 19",
    title: "Image 19",
    description: "Description coming soon.",
      "A dark, hat-like form frames the head, creating a hard boundary that contrasts with the softer textures of skin and background. Geometric lines and metallic tones intersect the face, suggesting instrumentation rather than ornament. The gaze is forward, composed, unyielding.\n\nThe circle acts as a protective field. It defines where pressure can enter and where it must stop. The image holds because it draws a clean perimeter around identity. Exposure is permitted only inside a structure that knows its limits.",
  },
  {
    id: 20,
    imageSrc: "/inner-climate/20.png",
    artworkNumber: "Artwork 20",
    title: "Image 20",
    description: "Description coming soon.",
      "The figure is bathed in cool blues and warm ambers simultaneously, as if standing at the intersection of opposing temperatures. The surface glows in places, fractures in others, but never tips fully toward heat or cold. The head tilts slightly, eyes closed, balanced between extremes.\n\nThis is a study in equilibrium under mixed conditions. Pressure arrives from multiple directions, each with a different demand, and the system answers by averaging rather than choosing. The image suggests a mature boundary: one that does not resolve tension by elimination, but by balance.",
  },
  {
    id: 21,
    imageSrc: "/inner-climate/21.png",
    artworkNumber: "Artwork 21",
    title: "Image 21",
    description: "Description coming soon.",
      "The face appears pressed close to the surface, as if proximity itself has increased density. Color and particulate matter concentrate along the contours, thickening the boundary where contact is most likely. Nothing spills inward. The pressure announces itself only through saturation, not deformation.\n\nThis image holds by accepting nearness without yielding interior ground. The surface becomes heavier, more deliberate, precisely where approach intensifies. What looks intimate is actually defensive mass. The system answers closeness by increasing thickness, not retreat.",
  },
  {
    id: 22,
    imageSrc: "/inner-climate/22.png",
    artworkNumber: "Artwork 22",
    title: "Image 22",
    description: "Description coming soon.",
      "A haze settles across the image like condensation, softening edges and muting contrast. The figure remains present but slightly delayed, as though clarity has been intentionally postponed. Light filters in slowly, never fully resolving the surface in a single register.\n\nThe delay is the mechanism. By slowing legibility, the image prevents premature interpretation from becoming control. Pressure is managed through timing rather than resistance. The portrait stays intact by deciding when it will be fully seen.",
  },
  {
    id: 23,
    imageSrc: "/inner-climate/23.png",
    artworkNumber: "Artwork 23",
    title: "Image 23",
    description: "Description coming soon.",
      "Multiple layers overlap the figure, each carrying a portion of the visual weight. No single plane bears responsibility for coherence. Textures stack, intersect, and partially cancel one another, creating a distributed structure that resists collapse.\n\nThis is stability through cooperation. The system does not rely on strength at one point, but on shared burden across many. Identity persists because it is not centralized. The image suggests that endurance is often collective, even when the subject stands alone.",
  },
  {
    id: 24,
    imageSrc: "/inner-climate/24.png",
    artworkNumber: "Artwork 24",
    title: "Image 24",
    description: "Description coming soon.",
      "Sharp lines and deliberate framing introduce a more architectural order. The face is positioned within a clear structural envelope, as if measured and set in place. Movement is minimal, tightly bounded, and intentional.\n\nThe work refuses expressive excess. By narrowing the range of allowable motion, it increases reliability. Pressure encounters rules instead of reaction. Calm here is procedural, not emotional. The image holds because it knows exactly how much movement it permits.",
  }
];
